export const ALL_SONG_METADATA = {
  "ragas": [
    "Abheri",
    "Abhogi",
    "Ahiri",
    "Amritavarshini",
    "Anandabhairavi",
    "Andolika",
    "Arabhi",
    "Asaveri",
    "Atana",
    "Begada",
    "Bhairavi",
    "Bhavapriya",
    "Bhupalam",
    "Bilahari",
    "Bowli",
    "Brindavana Saranga",
    "Chakravaham",
    "Charukesi",
    "Chathusra Jhampa",
    "Chittaranjani",
    "Deshadi",
    "Devagandhari",
    "Dhanyasi",
    "Dharmavathi",
    "Durbar",
    "Dwijavanti A.k.a. Jujavanthi",
    "Gowla",
    "Gowli Panthu",
    "Gowrimanohari",
    "Gurjjari",
    "Hamir Kalyani",
    "Hamsadhwani",
    "Hamsanada",
    "Hari Kambodhi",
    "Hemavathi",
    "Hindolam",
    "Hindolavasanta",
    "Isha Manohari",
    "Jaganmohini",
    "Janaranjani",
    "Jayantasena",
    "Kaikavaasi",
    "Kalyani",
    "Kamala Manohari",
    "Kambodhi",
    "Kanada",
    "Kannada",
    "Kapi",
    "Karnaranjani",
    "Karnataka Devagandhari Or Abheri",
    "Kedaragowla",
    "Kedaram",
    "Keeravani",
    "Kesari",
    "Khamas",
    "Kharaharapriya",
    "Kokilaaravam",
    "Kumudakriya",
    "Lalitha",
    "Lathangi",
    "Madhyamavati",
    "Malahari",
    "Malayamarutham",
    "Mandari",
    "Manji",
    "Mayamalavagowla",
    "Mohanam",
    "Mukhari",
    "Muthuswami Dikshitar",
    "Naga Gandhari",
    "Nalinakanti",
    "Narayanagaula",
    "Nasikabhooshani",
    "Nata Kuranji",
    "Natakapriya",
    "Nattai",
    "Nayaki",
    "Panthuvarali",
    "Pantuvarali",
    "Poorvikalyani",
    "Purnacandrika",
    "Ramapriya",
    "Ranjani",
    "Rasali",
    "Rasikapriya",
    "Ravichandrika",
    "Reethigowlai",
    "Revathi",
    "Rudrapriya",
    "Sahana",
    "Salaka Bhairavi",
    "Sama",
    "Saranga",
    "Saveri",
    "Shadvidhamargini",
    "Shankarabharanam",
    "Shanmukhapriya",
    "Shivapanthuvarali",
    "Shriranjani",
    "Shuddha Dhanyasi",
    "Shuddha Saveri",
    "Simhavahini",
    "Simhendramadhyamam",
    "Sowrastram",
    "Sri",
    "Sriranjani",
    "Suddha Simantini",
    "Surati",
    "Thodi",
    "Thoya Vegavahini",
    "Vachaspathi",
    "Valaji",
    "Varali",
    "Varamu",
    "Vasantha",
    "Vasanthabhairavi",
    "Visnupriya",
    "Yadukula Kambodhi",
    "Yamuna Kalyani"
  ],
  "talas": [
    "Adi",
    "Adi, Kalai",
    "Deshadi",
    "Dhruva Talam",
    "Eka",
    "Jhampa",
    "Khanda Ata Talam",
    "Khanda Chapu",
    "Khanda Ekam",
    "Matya",
    "Misra Chapu",
    "Rupakam",
    "Triputa"
  ],
  "composers": [
    "Ambujam Krishna",
    "Andal / Godai / Nachiyar",
    "Annamacharya",
    "Annaswami Shastri",
    "Appayya Dikshitar",
    "Arunachala Kavi",
    "Chengalvaraaya Shastri",
    "Chinni Krishna Dasa",
    "Gopalakrishna Bharati",
    "Hh Jayachamaraja Wodeyar",
    "Irayimman Thampi",
    "Kavi Kunjara Bharathi",
    "Kavi Mathruboddaya",
    "Kotishwara Iyer",
    "Kumara Ettendra",
    "Lalgudi Jayaraman",
    "Maha Vaidyanatha Sivan",
    "Meechu Krishna Iyer",
    "Muthaiah Bhagavatar",
    "Muthu Thandavar",
    "Muthuswami Dikshitar",
    "Mysore Sadashiva Rao",
    "Mysore Vasudevacharya",
    "Oothukkadu Venkata Kavi",
    "Paidala Gurumoorti Shastri",
    "Papanasam Sivan",
    "Patnam Subramanya Iyer",
    "Periaswamy Thooran",
    "Ponnaiah Pillai",
    "Poochi Srinivasa Iyengar",
    "Puliyur Doraiswamy Ayyar",
    "Purandara Dasa",
    "Ramaswami Shivan",
    "Sadasiva Brahmendra",
    "Shyama Shastry",
    "Subbaraya Shastri",
    "Swati Tirunal",
    "Thanjavur Shankara Iyer",
    "Tyagaraja",
    "V.v.srivatsa.",
    "Vyaasaraaya"
  ]
};